import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Layout from "../components/general/layout/layout.component";
import HomePage from "../components/views/home/home";


const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Amodular</title>
        <meta name="description" content="Generated by <<Kru360>>" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        <Layout>
        <HomePage/>







        </Layout>



    </div>
  )
}

export default Home
